### PR TITLE
Second deployment

### PR DESCRIPTION
**Pull request by willpill**
Second deployment of the Junior Caucus website.
Merging on Feb 5th.

### CODE REVIEW

**Review by Elias2660 — DISMISSED** [review]
Need to pass JC design review. 

Also, problems with people page, the transitions, and warnings with lottie files. 

Additional pages, such as socials and announcements are not working.

**Comment by willpill** [comment]
It's just a draft right now. We will deploy once we pass design review and fix some of the more pressing issues :)

**Review by connor132435 — APPROVED** [review]
Beautiful

**Review by ethannsie — COMMENTED** [review]
nice job 😊

**Review by yellowstonepark — APPROVED** [review]
looks good!

**Review by Elias2660 — APPROVED** [review]

**Pull request merged**
